'use strict'

var mongoose = require('mongoose')
var Schema = mongoose.Schema

var UserPermissionsSchema = new Schema({
  companyId: { type: Schema.ObjectId, ref: 'companyprofile' },
  userId: { type: Schema.ObjectId, ref: 'users' },
  connect_facebook_account: {type: Boolean, default: true},
  invite_members: {type: Boolean, default: true},
  delete_members: {type: Boolean, default: true},
  update_role: {type: Boolean, default: true},
  view_members: {type: Boolean, default: true},
  create_teams: {type: Boolean, default: true},
  view_teams: {type: Boolean, default: true},
  update_teams: {type: Boolean, default: true},
  delete_teams: {type: Boolean, default: true},
  view_subscribers: {type: Boolean, default: true},
  assign_tags: {type: Boolean, default: true},
  set_custom_fields: {type: Boolean, default: true},
  export_subscribers: {type: Boolean, default: true},
  create_custom_fields: {type: Boolean, default: true},
  view_custom_fields: {type: Boolean, default: true},
  update_custom_fields: {type: Boolean, default: true},
  delete_custom_fields: {type: Boolean, default: true},
  create_tags: {type: Boolean, default: true},
  view_tags: {type: Boolean, default: true},
  update_tags: {type: Boolean, default: true},
  delete_tags: {type: Boolean, default: true},
  create_broadcasts: {type: Boolean, default: true},
  view_broadcasts: {type: Boolean, default: true},
  create_polls: {type: Boolean, default: true},
  view_polls: {type: Boolean, default: true},
  delete_polls: {type: Boolean, default: true},
  view_poll_reports: {type: Boolean, default: true},
  resend_polls: {type: Boolean, default: true},
  create_surveys: {type: Boolean, default: true},
  view_surveys: {type: Boolean, default: true},
  delete_surveys: {type: Boolean, default: true},
  view_survey_reports: {type: Boolean, default: true},
  resend_surveys: {type: Boolean, default: true},
  create_segmentation_lists: {type: Boolean, default: true},
  view_segmentation_lists: {type: Boolean, default: true},
  update_segmentation_lists: {type: Boolean, default: true},
  delete_segmentation_lists: {type: Boolean, default: true},
  create_templates: {type: Boolean, default: true},
  view_templates: {type: Boolean, default: true},
  update_templates: {type: Boolean, default: true},
  delete_templates: {type: Boolean, default: true},
  create_comment_capture_rules: {type: Boolean, default: true},
  view_comment_capture_rules: {type: Boolean, default: true},
  update_comment_capture_rules: {type: Boolean, default: true},
  delete_comment_capture_rules: {type: Boolean, default: true},
  invite_subscribers_using_phone_number: {type: Boolean, default: true},
  manage_facebook_pages: {type: Boolean, default: true},
  set_persistent_menu: {type: Boolean, default: true},
  manage_welcome_message: {type: Boolean, default: true},
  manage_greeting_text: {type: Boolean, default: true},
  manage_livechat: {type: Boolean, default: true},
  unsubsubscribe_subscribers: {type: Boolean, default: true},
  assign_session_agent: {type: Boolean, default: true},
  assign_session_team: {type: Boolean, default: true},
  manage_advanced_settings: {type: Boolean, default: true},
  manage_billing: {type: Boolean, default: true},
  upgrade_service: {type: Boolean, default: true},
  downgrade_service: {type: Boolean, default: true},
  create_messenger_codes: {type: Boolean, default: true},
  view_messenger_codes: {type: Boolean, default: true},
  update_messenger_codes: {type: Boolean, default: true},
  delete_messenger_codes: {type: Boolean, default: true},
  create_messnger_ref_urls: {type: Boolean, default: true},
  view_messenger_ref_urls: {type: Boolean, default: true},
  update_messenger_ref_urls: {type: Boolean, default: true},
  delete_messenger_ref_urls: {type: Boolean, default: true},
  manage_integrations: {type: Boolean, default: true},
  manage_webhooks: {type: Boolean, default: true},
  delete_account_information: {type: Boolean, default: true},
  add_autoposting_feeds: {type: Boolean, default: true},
  view_autoposting_feeds: {type: Boolean, default: true},
  update_autoposting_feeds: {type: Boolean, default: true},
  delete_autoposting_feeds: {type: Boolean, default: true},
  enable_disable_autoposting_feeds: {type: Boolean, default: true},
  view_autoposting_feed_history: {type: Boolean, default: true},
  create_sequences: {type: Boolean, default: true},
  view_sequences: {type: Boolean, default: true},
  update_sequences: {type: Boolean, default: true},
  delete_sequences: {type: Boolean, default: true},
  create_sponsored_broadcast: {type: Boolean, default: true},
  create_campaign: {type: Boolean, default: true},
  create_adset: {type: Boolean, default: true},
  create_ad: {type: Boolean, default: true},
  update_sponsored_broadcast: {type: Boolean, default: true},
  view_sponsored_broadcast: {type: Boolean, default: true},
  delete_sponsored_broadcast: {type: Boolean, default: true},
  publish_sponsored_broadcast: {type: Boolean, default: true},
  schedule_sponsored_broadcast: {type: Boolean, default: true},
  create_bots: {type: Boolean, default: true},
  train_bots: {type: Boolean, default: true},
  update_bots: {type: Boolean, default: true},
  view_bots: {type: Boolean, default: true},
  delete_bots: {type: Boolean, default: true},
  add_rss_feeds: {type: Boolean, default: true},
  view_rss_fedds: {type: Boolean, default: true},
  update_rss_feeds: {type: Boolean, default: true},
  delete_rss_feeds: {type: Boolean, default: true},
  enable_disable_rss_feeds: {type: Boolean, default: true},
  view_rss_feed_history: {type: Boolean, default: true},
  add_news_feeds: {type: Boolean, default: true},
  view_news_fedds: {type: Boolean, default: true},
  update_news_feeds: {type: Boolean, default: true},
  delete_news_feeds: {type: Boolean, default: true},
  enable_disable_news_feeds: {type: Boolean, default: true},
  view_news_feed_history: {type: Boolean, default: true},
  update_news_feed_stories: {type: Boolean, default: true},
  create_chatbot_automation: {type: Boolean, default: true},
  update_chatbot_automation: {type: Boolean, default: true},
  configure_chatbot_automation: {type: Boolean, default: true},
  muteNotifications: [String],
  sla_dashboard: Boolean,
  configure_message_alerts: { type: Boolean: default: true }
})

module.exports = mongoose.model('permissions', UserPermissionsSchema)
